# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLeaveapplyasignleave():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_leaveapplyasignleave(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    self.driver.find_element(By.LINK_TEXT, "Leave").click()
    self.driver.find_element(By.LINK_TEXT, "Apply").click()
    self.driver.find_element(By.LINK_TEXT, "Assign Leave").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").send_keys("Orange  Test")
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(2) .oxd-input-group__label-wrapper")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
  
