# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPerformancemytrackers():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_performancemytrackers(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    self.driver.find_element(By.LINK_TEXT, "Performance").click()
    self.driver.find_element(By.LINK_TEXT, "My Trackers").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-header-cell:nth-child(1) > .oxd-table-header-sort > .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--active .oxd-table-header-sort-dropdown-item:nth-child(2) > .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-header-cell:nth-child(2) > .oxd-table-header-sort > .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--active .oxd-table-header-sort-dropdown-item:nth-child(2) > .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-header-cell:nth-child(3) > .oxd-table-header-sort > .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--active .oxd-table-header-sort-dropdown-item:nth-child(2) > .oxd-text").click()
    self.driver.find_element(By.NAME, "view").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".\\--negative path:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--deselected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--deselected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--deselected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--ghost").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-three-dots-vertical").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bi-three-dots-vertical")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-dropdown-item:nth-child(1) > .oxd-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\--active > .oxd-icon-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--deselected").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-three-dots-vertical").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bi-three-dots-vertical")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-dropdown-item:nth-child(2) > .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-three-dots-vertical").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bi-three-dots-vertical")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-dropdown-item:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--label-danger").click()
  
