# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDashboard():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dashboard(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-icon-button--solid-main > .oxd-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    element = self.driver.find_element(By.LINK_TEXT, "Dashboard")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-icon-button--success").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-icon-button--warn > .oxd-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-icon-button--danger > .oxd-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    element = self.driver.find_element(By.LINK_TEXT, "Dashboard")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-icon-button--info").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-icon-button > .oxd-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(2) .cls-1:nth-child(3)").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(6) .cls-1")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(3) > .oxd-icon-button > .oxd-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(3) > .oxd-icon-button .cls-1:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(3) > .oxd-icon-button .cls-1:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(4) .cls-1").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(5) > .oxd-icon-button > .oxd-icon").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(6) .cls-1").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .orangehrm-buzz-widget-header img").click()
    self.driver.find_element(By.LINK_TEXT, "Dashboard").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-gear-fill").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--ghost").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-gear-fill").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-switch-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
