# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuzz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buzz(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(12) .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-buzz-post-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-buzz-post-input").send_keys("asdfghjkl")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--main").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-glass-button:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-buzz-post--focus > .oxd-buzz-post-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-buzz-post--focus > .oxd-buzz-post-input").send_keys("asd")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-file-div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-dialog-close-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-glass-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-buzz-post--focus > .oxd-buzz-post-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-buzz-post--focus > .oxd-buzz-post-input").send_keys("asd")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-actions > .oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-dialog-close-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--active > .oxd-icon-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--active > .oxd-icon-button > .oxd-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--active > .oxd-icon-button > .oxd-icon").click()
    self.driver.find_element(By.ID, "heart-svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet .oxd-icon-button:nth-child(2) > .oxd-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet .oxd-icon-button:nth-child(2) > .oxd-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("asd")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-post-comment-action:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-post-comment-action:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("asdf")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-post-comment-action:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-post-comment-action:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--label-danger").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon-button").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon-button")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-buzz-post-header-config-item:nth-child(2) > .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-actions > .oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet .orangehrm-heart-icon-circle").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-buzz-post-header-config-item:nth-child(1) > .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--text:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(1) > .oxd-sheet > .orangehrm-buzz-post .oxd-icon-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-buzz-post-header-config-item:nth-child(1) > .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-trash").click()
  
