# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMyinfojobsalarytaxreport():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_myinfojobsalarytaxreport(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    element = self.driver.find_element(By.LINK_TEXT, "My Info")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "My Info").click()
    self.driver.find_element(By.LINK_TEXT, "Job").click()
    self.driver.find_element(By.CSS_SELECTOR, ".input-container-filename").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-switch-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(4) .oxd-grid-item:nth-child(1) .oxd-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(4) .oxd-grid-item:nth-child(1) .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(2) .oxd-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-file-div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-switch-input").click()
    self.driver.find_element(By.LINK_TEXT, "Salary").click()
    self.driver.find_element(By.LINK_TEXT, "Tax Exemptions").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-row:nth-child(3) .oxd-select-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(3) .oxd-input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-grid-item:nth-child(2) .oxd-input").click()
    self.driver.find_element(By.LINK_TEXT, "Report-to").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(2) > .orangehrm-container .oxd-table-cell:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(3) > .orangehrm-container .oxd-table-card:nth-child(1) .oxd-table-cell:nth-child(1) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(2) .oxd-table-cell:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(3) .oxd-table-cell:nth-child(1) > div").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(4) .oxd-table-cell:nth-child(1) > div").click()
  
