# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTimetimesheets():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_timetimesheets(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(4) .oxd-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").send_keys("Paul  Collings")
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-form")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--visited").click()
    self.driver.find_element(By.LINK_TEXT, "My Timesheets").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--prev").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-chevron-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-chevron-right").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\--prev").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-calendar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-calendar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-calendar").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-layout-context").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-autocomplete-text-input > input").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text--arrow").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-plus").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".bi-plus")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-timesheet-table-body-row:nth-child(2) > .\\--flex .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--secondary").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button:nth-child(1)").click()
  
