# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRecruitmentvacancies():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_recruitmentvacancies(self):
    self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index")
    self.driver.set_window_size(1056, 608)
    element = self.driver.find_element(By.LINK_TEXT, "My Info")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(5) .oxd-text")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-main-menu-item-wrapper:nth-child(5) .oxd-text").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Vacancies").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text--after > .bi-caret-up-fill").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-actions")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-input--focus").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-select-text-input").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--ghost").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(8) .oxd-table-card-cell-checkbox .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(8) .oxd-icon-button:nth-child(2) > .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".bi-plus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-file-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea--focus").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-textarea--focus").send_keys("test")
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-actions:nth-child(5) > .oxd-button--secondary").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-form-actions:nth-child(5) > .oxd-button--secondary")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.LINK_TEXT, "Vacancies").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(8) .oxd-table-card-cell-checkbox .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(8) .oxd-icon-button:nth-child(1) > .oxd-icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-button--text").click()
    self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(8) .oxd-icon-button:nth-child(1) > .oxd-icon").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".oxd-table-card:nth-child(8) .oxd-icon-button:nth-child(1) > .oxd-icon")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".orangehrm-button-margin:nth-child(2)").click()
  
